POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{ "title": "first blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress.fi",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{ "title": "second blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress2.fi",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{ "title": "third blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress3.fi",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{ "title": "fourth blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress3.fi",
  "likes": 1
}