POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlcjIiLCJpZCI6IjY0Mzc5ZjNmZjBmNTYxNGFmODU3MzQzOCIsImlhdCI6MTY4MTM2Njg4NywiZXhwIjoxNjgxMzY2OTQ3fQ.TNgqC37xd9Gi_fTZbjm9Ytj59bsqkYWGZfeaK-UDIHw

{ "title": "first blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress.fi",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlcjIiLCJpZCI6IjY0MzZjODgwNDlmOGQ5YjNiNDc0YjUzOCIsImlhdCI6MTY4MTMxMTkyNX0.xE7R4iM4eQloqbM-jG6zUmf-YzUYybnmFPdaJS13PHA

{ "title": "second blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress2.fi",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{ "title": "third blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress3.fi",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{ "title": "fourth blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress3.fi",
  "likes": 1
}