POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlcjIiLCJpZCI6IjY0MzdjM2QwMjVlYjM4YzFiZTNmNTc1NyIsImlhdCI6MTY4MTM3NjI1NSwiZXhwIjoxNjgxMzgzNDU1fQ.CglVBXsZ3cv-IQ6bdw06Fk9ArJHmFwwH4zFU1ftYBTg

{ "title": "first blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress.fi",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlcjIiLCJpZCI6IjY0MzdjM2QwMjVlYjM4YzFiZTNmNTc1NyIsImlhdCI6MTY4MTM3NjI1NSwiZXhwIjoxNjgxMzgzNDU1fQ.CglVBXsZ3cv-IQ6bdw06Fk9ArJHmFwwH4zFU1ftYBTg

{ "title": "second blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress2.fi",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{ "title": "third blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress3.fi",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{ "title": "fourth blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress3.fi",
  "likes": 1
}