POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlcjIiLCJpZCI6IjY0MzdhZjg5YWNmOTY5NTIyZTlmNzM5MiIsImlhdCI6MTY4MTM3MTQ0OSwiZXhwIjoxNjgxMzc4NjQ5fQ.c0eEVmDi4EA0BvLUvLefL6ZAOebtu1G-9pGuXiqXhvI

{ "title": "first blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress.fi",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json
Authorization: Bearer x

{ "title": "second blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress2.fi",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{ "title": "third blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress3.fi",
  "likes": 1
}

###

POST http://localhost:3003/api/blogs/ HTTP/1.1 
content-type: application/json

{ "title": "fourth blog",
  "author": "Matias Mäkynen",
  "url": "http://imaginary-adress3.fi",
  "likes": 1
}